import type { Task, TaskCategory } from '../../types/task';

export const taskCategoryLabels: Record<'all' | TaskCategory, string> = {
  all: '全部',
  health: '健康',
  fitness: '运动',
  diet: '饮食',
  sleep: '睡眠',
  study: '学习',
  work: '工作',
  life: '生活',
  custom: '自定义',
};

export const starterTasks: Task[] = [
  {
    id: 'water-2000',
    title: '喝水 2000ml',
    description: '让身体保持充足水分',
    category: 'health',
    type: 'daily',
    expReward: 10,
    coinReward: 10,
    completed: false,
    target: 2000,
    current: 0,
    unit: 'ml',
  },
  {
    id: 'exercise-30',
    title: '运动 30 分钟',
    description: '散步、跑步或力量训练都可以',
    category: 'fitness',
    type: 'daily',
    expReward: 30,
    coinReward: 20,
    completed: false,
    target: 30,
    current: 0,
    unit: '分钟',
  },
  {
    id: 'healthy-meal',
    title: '完成一顿健康饮食',
    description: '记录一次让自己满意的饮食选择',
    category: 'diet',
    type: 'daily',
    expReward: 15,
    coinReward: 10,
    completed: false,
  },
  {
    id: 'sleep-before-2330',
    title: '23:30 前准备入睡',
    description: '给今天一个安静的结尾',
    category: 'sleep',
    type: 'daily',
    expReward: 20,
    coinReward: 15,
    completed: false,
  },
  {
    id: 'read-20',
    title: '阅读 20 分钟',
    description: '积累一点新的知识',
    category: 'study',
    type: 'daily',
    expReward: 20,
    coinReward: 15,
    completed: false,
    target: 20,
    current: 0,
    unit: '分钟',
  },
];
